# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 434)
        MainWindow.setMinimumSize(QtCore.QSize(368, 434))
        MainWindow.setMaximumSize(QtCore.QSize(368, 434))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.689, y1:0.233, x2:0.578, y2:0.136273, stop:0.0945274 rgba(83, 79, 20, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainWindow_Header = QtWidgets.QLabel(self.centralwidget)
        self.MainWindow_Header.setGeometry(QtCore.QRect(10, 10, 271, 101))
        self.MainWindow_Header.setStyleSheet("font: 18pt \"Comic Sans MS\";")
        self.MainWindow_Header.setObjectName("MainWindow_Header")
        self.Area_button = QtWidgets.QPushButton(self.centralwidget)
        self.Area_button.setEnabled(True)
        self.Area_button.setGeometry(QtCore.QRect(70, 170, 231, 71))
        self.Area_button.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-radius : 15; \n"
"background-color: rgb(255, 233, 188);\n"
"                              border : 2px solid black\n"
"")
        self.Area_button.setObjectName("Area_button")
        self.Perimeter_button = QtWidgets.QPushButton(self.centralwidget)
        self.Perimeter_button.setGeometry(QtCore.QRect(70, 280, 231, 71))
        self.Perimeter_button.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-radius : 15; \n"
"background-color: rgb(255, 233, 188);\n"
"                              border : 2px solid black\n"
"")
        self.Perimeter_button.setObjectName("Perimeter_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainWindow_Header.setText(_translate("MainWindow", "Shapes Calculator"))
        self.Area_button.setText(_translate("MainWindow", "Area"))
        self.Perimeter_button.setText(_translate("MainWindow", "Perimeter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
