# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rectangle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 434)
        MainWindow.setMinimumSize(QtCore.QSize(368, 434))
        MainWindow.setMaximumSize(QtCore.QSize(368, 434))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.689, y1:0.233, x2:0.578, y2:0.136273, stop:0.0945274 rgba(83, 79, 20, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Rectangle_Shape = QtWidgets.QPushButton(self.centralwidget)
        self.Rectangle_Shape.setGeometry(QtCore.QRect(50, 110, 271, 171))
        self.Rectangle_Shape.setStyleSheet("\n"
"background-color: rgb(114, 199, 205);\n"
"                              border : 2px solid black\n"
"")
        self.Rectangle_Shape.setText("")
        self.Rectangle_Shape.setObjectName("Rectangle_Shape")
        self.Rectangle_Width = QtWidgets.QLineEdit(self.centralwidget)
        self.Rectangle_Width.setGeometry(QtCore.QRect(160, 290, 31, 22))
        self.Rectangle_Width.setObjectName("Rectangle_Width")
        self.Rectangle_Height = QtWidgets.QLineEdit(self.centralwidget)
        self.Rectangle_Height.setGeometry(QtCore.QRect(330, 170, 31, 22))
        self.Rectangle_Height.setObjectName("Rectangle_Height")
        self.Rectangle_Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Rectangle_Submit.setGeometry(QtCore.QRect(210, 370, 141, 51))
        self.Rectangle_Submit.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-radius : 15; \n"
"background-color: rgb(255, 233, 188);\n"
"                              border : 2px solid black\n"
"")
        self.Rectangle_Submit.setObjectName("Rectangle_Submit")
        self.Rectangle_Label = QtWidgets.QLabel(self.centralwidget)
        self.Rectangle_Label.setGeometry(QtCore.QRect(90, 320, 281, 41))
        self.Rectangle_Label.setStyleSheet("font: 15pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.Rectangle_Label.setObjectName("Rectangle_Label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Rectangle_Submit.setText(_translate("MainWindow", "Submit"))
        self.Rectangle_Label.setText(_translate("MainWindow", "Enter height and width"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
