# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Shapes_Selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shapes_Selecter(object):
    def setupUi(self, Shapes_Selecter):
        Shapes_Selecter.setObjectName("Shapes_Selecter")
        Shapes_Selecter.resize(368, 434)
        Shapes_Selecter.setMinimumSize(QtCore.QSize(368, 434))
        Shapes_Selecter.setMaximumSize(QtCore.QSize(368, 434))
        Shapes_Selecter.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.689, y1:0.233, x2:0.578, y2:0.136273, stop:0.0945274 rgba(83, 79, 20, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(Shapes_Selecter)
        self.centralwidget.setObjectName("centralwidget")
        self.Square_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Square_Button.setGeometry(QtCore.QRect(50, 80, 91, 91))
        self.Square_Button.setStyleSheet("border-radius : 50; \n"
"background-color: rgb(174, 149, 255);\n"
"                              border : 2px solid black\n"
"")
        self.Square_Button.setText("")
        self.Square_Button.setObjectName("Square_Button")
        self.Circle_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Circle_Button.setGeometry(QtCore.QRect(220, 70, 101, 101))
        self.Circle_Button.setStyleSheet("border-radius : 50; \n"
"background-color: rgb(0, 255, 72);\n"
"                              border : 2px solid black")
        self.Circle_Button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Circle_Button.setText("")
        self.Circle_Button.setObjectName("Circle_Button")
        self.Triangle_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Triangle_Button.setGeometry(QtCore.QRect(220, 240, 101, 81))
        self.Triangle_Button.setStyleSheet("background-color:rgba(0, 0, 0, 0)")
        self.Triangle_Button.setText("")
        self.Triangle_Button.setObjectName("Triangle_Button")
        self.Shapes_TriangleImage = QtWidgets.QLabel(self.centralwidget)
        self.Shapes_TriangleImage.setGeometry(QtCore.QRect(210, 230, 121, 91))
        self.Shapes_TriangleImage.setStyleSheet("background-image: url(:/triangle/triangle.png);")
        self.Shapes_TriangleImage.setText("")
        self.Shapes_TriangleImage.setPixmap(QtGui.QPixmap(":/triangle/triangle.png"))
        self.Shapes_TriangleImage.setScaledContents(True)
        self.Shapes_TriangleImage.setObjectName("Shapes_TriangleImage")
        self.Rectangle_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Rectangle_Button.setGeometry(QtCore.QRect(50, 240, 141, 91))
        self.Rectangle_Button.setStyleSheet("\n"
"background-color: rgb(114, 199, 205);\n"
"                              border : 2px solid black\n"
"")
        self.Rectangle_Button.setText("")
        self.Rectangle_Button.setObjectName("Rectangle_Button")
        self.Selector_Label = QtWidgets.QLabel(self.centralwidget)
        self.Selector_Label.setGeometry(QtCore.QRect(120, 360, 111, 16))
        self.Selector_Label.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.Selector_Label.setObjectName("Selector_Label")
        self.Shapes_TriangleImage.raise_()
        self.Square_Button.raise_()
        self.Circle_Button.raise_()
        self.Triangle_Button.raise_()
        self.Rectangle_Button.raise_()
        self.Selector_Label.raise_()
        Shapes_Selecter.setCentralWidget(self.centralwidget)

        self.retranslateUi(Shapes_Selecter)
        QtCore.QMetaObject.connectSlotsByName(Shapes_Selecter)

    def retranslateUi(self, Shapes_Selecter):
        _translate = QtCore.QCoreApplication.translate
        Shapes_Selecter.setWindowTitle(_translate("Shapes_Selecter", "MainWindow"))
        self.Selector_Label.setText(_translate("Shapes_Selecter", "Select Shape"))
import Shapes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Shapes_Selecter = QtWidgets.QMainWindow()
    ui = Ui_Shapes_Selecter()
    ui.setupUi(Shapes_Selecter)
    Shapes_Selecter.show()
    sys.exit(app.exec_())
