# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Triangle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 434)
        MainWindow.setMinimumSize(QtCore.QSize(368, 434))
        MainWindow.setMaximumSize(QtCore.QSize(368, 434))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.689, y1:0.233, x2:0.578, y2:0.136273, stop:0.0945274 rgba(83, 79, 20, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Triangle_Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Triangle_Submit.setGeometry(QtCore.QRect(220, 370, 141, 51))
        self.Triangle_Submit.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-radius : 15; \n"
"background-color: rgb(255, 233, 188);\n"
"                              border : 2px solid black\n"
"")
        self.Triangle_Submit.setObjectName("Triangle_Submit")
        self.Triangle_Label = QtWidgets.QLabel(self.centralwidget)
        self.Triangle_Label.setGeometry(QtCore.QRect(80, 300, 281, 41))
        self.Triangle_Label.setStyleSheet("font: 15pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.Triangle_Label.setObjectName("Triangle_Label")
        self.Triangle_Shape = QtWidgets.QLabel(self.centralwidget)
        self.Triangle_Shape.setGeometry(QtCore.QRect(80, 70, 211, 191))
        self.Triangle_Shape.setStyleSheet("background-image: url(:/triangle/triangle.png);")
        self.Triangle_Shape.setText("")
        self.Triangle_Shape.setPixmap(QtGui.QPixmap(":/triangle/triangle.png"))
        self.Triangle_Shape.setScaledContents(True)
        self.Triangle_Shape.setObjectName("Triangle_Shape")
        self.Triangle_Base = QtWidgets.QLineEdit(self.centralwidget)
        self.Triangle_Base.setGeometry(QtCore.QRect(170, 270, 31, 22))
        self.Triangle_Base.setObjectName("Triangle_Base")
        self.Triangle_Height = QtWidgets.QLineEdit(self.centralwidget)
        self.Triangle_Height.setGeometry(QtCore.QRect(170, 150, 31, 22))
        self.Triangle_Height.setObjectName("Triangle_Height")
        self.Triangle_Side_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Triangle_Side_1.setGeometry(QtCore.QRect(250, 150, 31, 22))
        self.Triangle_Side_1.setObjectName("Triangle_Side_1")
        self.Triangle_Side_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Triangle_Side_2.setGeometry(QtCore.QRect(90, 150, 31, 22))
        self.Triangle_Side_2.setObjectName("Triangle_Side_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Triangle_Submit.setText(_translate("MainWindow", "Submit"))
        self.Triangle_Label.setText(_translate("MainWindow", "Enter base and height"))
import Shapes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
